import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  quantizePalette,
  dominantPaletteColor,
  PALETTE_FALLBACK,
} from "./androidPalette.js";

// Reference generated by scripts/album-colors/PaletteStudy.java with
// -Dpalette.fixtures=true, using official AndroidX Palette 1.0.0 on Android.
const reference = JSON.parse(
  readFileSync(new URL("./fixtures/androidPalette.json", import.meta.url)),
);
for (const sample of reference.samples) {
  test(`matches AndroidX swatches and populations for cover ${sample.file}`, () => {
    const pixels = [];
    for (const [c, count] of sample.histogram) {
      for (let i = 0; i < count; i++)
        pixels.push((c >> 10) << 3, ((c >> 5) & 31) << 3, (c & 31) << 3, 255);
    }
    const actual = quantizePalette(pixels);
    assert.deepEqual(
      actual,
      sample.swatches.map((s) => ({ ...s, color: s.color.toLowerCase() })),
    );
    const dominant = sample.swatches.reduce((a, b) =>
      a.population >= b.population ? a : b,
    );
    assert.equal(dominantPaletteColor(pixels), dominant.color.toLowerCase());
  });
}

test("empty, transparent, black and white artwork uses the neutral fallback", () => {
  for (const pixels of [
    [],
    [255, 0, 0, 0],
    [0, 0, 0, 255],
    [255, 255, 255, 255],
  ]) {
    assert.equal(dominantPaletteColor(pixels), PALETTE_FALLBACK);
  }
});

test("small palettes retain 5-bit colors and choose by population", () => {
  assert.equal(
    dominantPaletteColor([255, 0, 0, 255, 0, 0, 255, 255, 0, 0, 255, 255]),
    "#0000f8",
  );
});
